src/Entity/Adresse.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdresseRepository")
 * @UniqueEntity( fields = {"adresse", "adresse_suite", "code_postal", "ville", "pays"} )
 */
class Adresse
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse_suite = "";

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal = "";

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $continent;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pays;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="adresses", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $entreprise;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Stage", mappedBy="adresse", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $stages;

    /**
     * Adresse constructor.
     */
    public function __construct()
    {
        $this->stages = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    /**
     * @param string $adresse
     * @return $this
     */
    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getAdresseSuite(): ?string
    {
        return $this->adresse_suite;
    }

    /**
     * @param string|null $adresse_suite
     * @return $this
     */
    public function setAdresseSuite(?string $adresse_suite): self
    {
        $this->adresse_suite = $adresse_suite;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    /**
     * @param string|null $code_postal
     * @return $this
     */
    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getVille(): ?string
    {
        return $this->ville;
    }

    /**
     * @param string $ville
     * @return $this
     */
    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    /**
     * @param string $latitude
     * @return $this
     */
    public function setLatitude(string $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    /**
     * @param string $longitude
     * @return $this
     */
    public function setLongitude(string $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getContinent(): ?string
    {
        return $this->continent;
    }

    /**
     * @param string $continent
     * @return $this
     */
    public function setContinent(string $continent): self
    {
        $this->continent = $continent;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPays(): ?string
    {
        return $this->pays;
    }

    /**
     * @param string $pays
     * @return $this
     */
    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    /**
     * @return Entreprise|null
     */
    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    /**
     * @param Entreprise|null $entreprise
     * @return $this
     */
    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    /**
     * @return Collection|Stage[]
     */
    public function getStages(): Collection
    {
        return $this->stages;
    }

    /**
     * @param Stage $stage
     * @return $this
     */
    public function addStage(Stage $stage): self
    {
        if (!$this->stages->contains($stage)) {
            $this->stages[] = $stage;
            $stage->setAdresse($this);
        }

        return $this;
    }

    /**
     * @param Stage $stage
     * @return $this
     */
    public function removeStage(Stage $stage): self
    {
        if ($this->stages->contains($stage)) {
            $this->stages->removeElement($stage);
            // set the owning side to null (unless already changed)
            if ($stage->getAdresse() === $this) {
                $stage->setAdresse(null);
            }
        }

        return $this;
    }
}

src/Entity/Stage.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StageRepository")
 * @UniqueEntity( fields = {"sujet", "intitule", "annee", "nom_etud", "prenom_etud", "promo", "annee_form", "departement"} )
 */
class Stage
{
    //Enumération des départements
    public const DEPARTEMENT = [
        0 => "G.M",
        1 => "G.P",
        2 => "G.B",
        3 => "G.C",
        4 => "G.E"
    ];

    //Enumération des années
    public const ANNEE_FORM = [
        0 => "3A",
        1 => "4A",
        2 => "5A"
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sujet;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $intitule;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree_jours;

    /**
     * @ORM\Column(type="boolean")
     */
    private $est_gratifie = false;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $gratification;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_etud;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom_etud;

    /**
     * @ORM\Column(type="boolean")
     */
    private $contratPro = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_tuteur_ent;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom_tuteur_ent;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $tel_tuteur_ent;

    /**
     * @ORM\Column(type="boolean")
     */
    private $mail_visible = true;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail_tuteur_ent;

    /**
     * @ORM\Column(type="string", length=1023, nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $recap;

    /**
     * @ORM\Column(type="boolean")
     */
    private $embauche = false;

    /**
     * @ORM\Column(type="integer")
     */
    private $promo;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee_form;

    /**
     * @ORM\Column(type="integer")
     */
    private $departement;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Adresse", inversedBy="stages", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $adresse;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Theme", inversedBy="stages", cascade={"persist"})
     */
    private $themes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\MotCle", inversedBy="stages", cascade={"persist"})
     */
    private $motsCles;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="stages", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $entreprise;

    /**
     * Stage constructor.
     */
    public function __construct()
    {
        $this->themes = new ArrayCollection();
        $this->motsCles = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getSlug(): string{
        return (new Slugify())->slugify($this->intitule);
    }

    /**
     * @return string|null
     */
    public function getSujet(): ?string
    {
        return $this->sujet;
    }

    /**
     * @param string $sujet
     * @return $this
     */
    public function setSujet(string $sujet): self
    {
        $this->sujet = $sujet;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    /**
     * @param string $intitule
     * @return $this
     */
    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getAnnee(): ?int
    {
        return $this->annee;
    }

    /**
     * @param int $annee
     * @return $this
     */
    public function setAnnee(int $annee): self
    {
        $this->annee = $annee;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getDureeJours(): ?int
    {
        return $this->duree_jours;
    }

    /**
     * @param int $duree_jours
     * @return $this
     */
    public function setDureeJours(int $duree_jours): self
    {
        $this->duree_jours = $duree_jours;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getEstGratifie(): ?bool
    {
        return $this->est_gratifie;
    }

    /**
     * @param bool $est_gratifie
     * @return $this
     */
    public function setEstGratifie(bool $est_gratifie): self
    {
        $this->est_gratifie = $est_gratifie;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getGratification(): ?float
    {
        return $this->gratification;
    }

    /**
     * @param int|null $gratification
     * @return $this
     */
    public function setGratification(?int $gratification): self
    {
        $this->gratification = $gratification;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getNomEtud(): ?string
    {
        return $this->nom_etud;
    }

    /**
     * @param string $nom_etud
     * @return $this
     */
    public function setNomEtud(string $nom_etud): self
    {
        $this->nom_etud = $nom_etud;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPrenomEtud(): ?string
    {
        return $this->prenom_etud;
    }

    /**
     * @param string $prenom_etud
     * @return $this
     */
    public function setPrenomEtud(string $prenom_etud): self
    {
        $this->prenom_etud = $prenom_etud;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getContratPro(): ?bool
    {
        return $this->contratPro;
    }

    /**
     * @param bool $contratPro
     * @return $this
     */
    public function setContratPro(bool $contratPro): self
    {
        $this->contratPro = $contratPro;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getNomTuteurEnt(): ?string
    {
        return $this->nom_tuteur_ent;
    }

    /**
     * @param string $nom_tuteur_ent
     * @return $this
     */
    public function setNomTuteurEnt(string $nom_tuteur_ent): self
    {
        $this->nom_tuteur_ent = $nom_tuteur_ent;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getPrenomTuteurEnt(): ?string
    {
        return $this->prenom_tuteur_ent;
    }

    /**
     * @param string $prenom_tuteur_ent
     * @return $this
     */
    public function setPrenomTuteurEnt(string $prenom_tuteur_ent): self
    {
        $this->prenom_tuteur_ent = $prenom_tuteur_ent;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getTelTuteurEnt(): ?string
    {
        return $this->tel_tuteur_ent;
    }

    /**
     * @param string|null $tel_tuteur_ent
     * @return $this
     */
    public function setTelTuteurEnt(?string $tel_tuteur_ent): self
    {
        $this->tel_tuteur_ent = $tel_tuteur_ent;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getMailVisible(): ?bool
    {
        return $this->mail_visible;
    }

    /**
     * @param bool $mail_visible
     * @return $this
     */
    public function setMailVisible(bool $mail_visible): self
    {
        $this->mail_visible = $mail_visible;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getMailTuteurEnt(): ?string
    {
        return $this->mail_tuteur_ent;
    }

    /**
     * @param string $mail_tuteur_ent
     * @return $this
     */
    public function setMailTuteurEnt(string $mail_tuteur_ent): self
    {
        $this->mail_tuteur_ent = $mail_tuteur_ent;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    /**
     * @param string|null $commentaire
     * @return $this
     */
    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getRecap(): ?string
    {
        return $this->recap;
    }

    /**
     * @param string|null $recap
     * @return $this
     */
    public function setRecap(?string $recap): self
    {
        $this->recap = $recap;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getEmbauche(): ?bool
    {
        return $this->embauche;
    }

    /**
     * @param bool $embauche
     * @return $this
     */
    public function setEmbauche(bool $embauche): self
    {
        $this->embauche = $embauche;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getPromo(): ?int
    {
        return $this->promo;
    }

    /**
     * @param int $promo
     * @return $this
     */
    public function setPromo(int $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getAnneeForm(): ?int
    {
        return $this->annee_form;
    }

    /**
     * Retourne la valeur de l'année (au lieu de la clé)
     *

src/Controller/StageController.php
<?php


namespace App\Controller;


use App\Entity\Search\StageSearch;
use App\Entity\Stage;
use App\Form\StageSearchType;
use App\Repository\StageRepository;
use App\Repository\ThemeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StageController extends  AbstractController
{

    private const CURRENT_MENU = "stage";
    /**
     * @var StageRepository
     */
    private $repo;

    /**
     * StageController constructor.
     * @param StageRepository $repo
     */
    public function __construct(StageRepository $repo)
    {
        $this->repo = $repo;
    }

    /**
     * Affiche la page de recherche de stage
     * Traite le formulaire de filtrage
     *
     * @Route("/stages", name="stage.index")
     * @param Request $request
     * @param ThemeRepository $themeRepo
     * @return Response
     */
    public function index(Request $request, ThemeRepository $themeRepo): Response
    {
        $search = new StageSearch();
        $form = $this->createForm(StageSearchType::class, $search);
        $form->handleRequest($request);

        $stages = $this->repo->filtrerStages($search, $themeRepo);
        return $this->render("stage/index.html.twig", [
            "current_menu" => self::CURRENT_MENU,
            "stages" => $stages,
            "form" => $form->createView()
        ]);
    }

    /**
     * Affiche les détails d'un stage
     *
     * @Route("/stages/{slug}-{id}", name="stage.show", requirements={"slug": "[a-z0-9\-]*"}))
     * @param int $id
     * @return Response
     */
    public function show(Stage $stage){
        return $this->render("stage/show.html.twig", [
            "current_menu" => self::CURRENT_MENU,
            "stage" => $stage
        ]);
    }

}

templates/stage/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Rechercher Stage' %}

{% block stylesheets %}
    <link href="{{ asset('/ressources/css/stageRecherche.css') }}" rel="stylesheet" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block body %}
    <div class="result-search-and-filter">
        <div class="filtre-expand-button">
            <button class="btn btn-light btn-block" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Filtrer les recherches<i class="fa fa-angle-down ml-4"></i>
            </button>
        </div>

        <div class="collapse" id="collapseExample">
            <div class="filter-container">
                <div class="form-input-container mt-4">

                    <div class="form_search_advice">*Utiliser le séparateur ";" entre plusieurs éléments (ex: Paris; Lyon)</div>
                    {{ form_start(form) }}
                    <div class="row ml-0 mr-0" >
                        {{ form_row(form.ville) }}
                        <p class="ou">ou</p>
                        {{ form_row(form.pays) }}
                        <p class="ou">ou</p>
                        {{ form_row(form.continent) }}
                        {{ form_row(form.annee) }}
                        {{ form_row(form.entreprise) }}

                    </div>
                    <div class="row ml-0 mr-0">
                        <div class="select2_form_item">
                            {{ form_row(form.themes ) }}
                        </div>
                        <div class="select2_form_item">
                            {{ form_row(form.motsCles) }}
                        </div>
                        {{ form_row(form.duree_mois_min) }}
                        {{ form_row(form.duree_mois_max) }}
                        <div class="checkboxes row">
                            {{ form_row(form.est_gratifie) }}
                            {{ form_row(form.embauche) }}
                            {{ form_row(form.contratPro) }}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-secondary mb-4">Filtrer</button>
                    {{ form_end(form, {'render_rest': false}) }}
                </div>
            </div>
        </div>
        <div class="row search-container">
            <div class="col-6 mt-4 map" id="map">
            </div>
            <div class="col-6 mt-4 result-container">
                <div class="row">
                    {%  for stage in stages %}
                        <div class="col-6 d-flex align-items-stretch">
                            <div class="card mb-4" >
                                <a class="card-body js-marker"
                                     id="stage-{{ stage.id }}" data-lat="{{ stage.adresse.latitude }}" data-lng="{{ stage.adresse.longitude }}"
                                     href="{{ path('stage.show', {id: stage.id, slug: stage.slug}) }}">
                                    <h5 class="card-title" id="card-title">
                                        {{ stage.intitule }}
                                    </h5>
                                    <div class="card-text">
                                        <div class="container">
                                            <div class="row">
                                                <p> <strong>{{ stage.adresse.entreprise.nom }}</strong></p>
                                            </div>
                                            <div class="row">
                                                <p class="mr-2">{{ stage.adresse.ville }}</p>
                                                <p class="mr-2">({{ stage.adresse.codePostal }})</p>
                                                <p>{{ stage.adresse.pays }}</p>
                                            </div>
                                            <div class="row">
                                                <p>Durée: {{ stage.dureeJours }} jours</p>
                                            </div>
                                            <div class="row">
                                                <p>Année: {{ stage.annee }}</p>
                                            </div>

                                            <div class="row icones">
                                                {% if stage.estGratifie %}
                                                    <div class="col">
                                                        <i class="fa fa-money" data-toggle="tooltip" data-placement="left" title="Ce stage était rémunéré"></i>
                                                    </div>
                                                {% endif %}
                                                {% if stage.embauche %}
                                                    <div class="col">
                                                        <i class="fa fa-briefcase" data-toggle="tooltip" data-placement="left" title="Ce stage a mené à une embauche"></i>
                                                    </div>
                                                {% endif %}
                                                {% if stage.contratPro %}
                                                    <div class="col">
                                                        <i class="fa fa-wrench" data-toggle="tooltip" data-placement="left" title="C'est un contrat pro"></i>
                                                    </div>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% else %}
                        <div class="no-result">
                            <h4>Désolé, aucun stage ne correspond à votre recherche...</h4>
                            <div class="no-found-image">

                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>



{% endblock %}

{% block javascripts %}
    <script src="{{ asset('/ressources/js/vendor.js') }}"></script>
    <script src="{{ asset('/ressources/js/app.map.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>

    <script>
        $('select').select2({
            language: "fr"
        });
    </script>

{% endblock %}

templates/stage/show.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link href="{{ asset('/ressources/css/stageDetail.css') }}" rel="stylesheet" />
{% endblock %}

{% block title stage.intitule %}

{% block body %}
    <div class="body">
        <a class="ml-1" href="{{ path('stage.index') }}">
            <div class="btn btn-sm btn-outline-secondary mt-1">
                <i class="fa fa-angle-left mr-4"></i>Retourner à la recherche des stages
            </div>
        </a>

        <div class="stage-detail col-9 mt-4 mb-4">
            <h1 class="text-center mb-4 mt-4">{{ stage.intitule }}</h1>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <p class="sujet-stage"><strong>Sujet:</strong> {{ stage.sujet }}</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        Ce stage a été réalisé en <strong>{{ stage.annee }}</strong> et a duré <strong>{{ stage.dureeJours }} jours</strong>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6 mt-4">
                        <strong>Information sur l'étudiant lors de la réalisation du stage:</strong>

                        <table class="table table-striped mt-2 mr-1 ">
                            <tbody>
                            <tr>
                                <th>Nom</th>
                                <td>{{ stage.nomEtud }}</td>
                            </tr>
                            <tr>
                                <th>Prénom</th>
                                <td>{{ stage.prenomEtud }}</td>
                            </tr>
                            <tr>
                                <th>Promotion</th>
                                <td>{{ stage.promo }}</td>
                            </tr>
                            <tr>
                                <th>Année formation</th>
                                <td>{{ stage.anneeFormType }}</td>
                            </tr>
                            <tr>
                                <th>Département</th>
                                <td>{{ stage.departementType }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="col-6 mt-4">
                        <strong>Information sur le stage:</strong>

                        <table class="table table-striped mt-2 ml-1 ">
                            <tbody>
                            <tr>
                                <th>Entreprise</th>
                                <td>{{ stage.adresse.entreprise.nom }} ({{ stage.adresse.entreprise.estPriveeType }})</td>
                            </tr>
                            <tr>
                                <th>Adresse</th>
                                <td>{{ stage.adresse.adresse }} - {{ stage.adresse.adresseSuite }}</td>
                            </tr>
                            <tr>
                                <th>Ville</th>
                                <td>{{ stage.adresse.ville }} ({{ stage.adresse.codePostal }})</td>
                            </tr>
                            <tr>
                                <th>Pays</th>
                                <td>{{ stage.adresse.pays }}</td>
                            </tr>
                            <tr>
                                <th>Continent</th>
                                <td> {{ stage.adresse.continent }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>

                </div>

                <br/>
                <div class="row ml-1">
                    <p><strong>Informations complémentaires:</strong></p>
                </div>
                <div class="row ml-1">
                    <div class="col">
                        {% if stage.estGratifie %}<p style="color: green"><i class="fa fa-money mr-1"></i> Le stage est gratifié</p>
                        {% else %} <p style="color: red"><i class="fa fa-times mr-1"></i>Le stage n'est pas gratifié</p>
                        {% endif %}
                    </div>
                    <!-- if estAdmin -> valeur -->
                    <div class="col">
                        {% if stage.contratPro %}<p style="color: green"><i class="fa fa-wrench mr-1"></i> Le stage est un contrat pro</p>
                        {% else %} <p style="color: red"><i class="fa fa-times mr-1"></i>Le stage n'est pas un contrat pro</p>
                        {% endif %}
                    </div>

                    <div class="col">
                        {% if stage.embauche %}<p style="color: green"><i class="fa fa-briefcase mr-1"></i> Le stage a mené à une embauche</p>
                        {% else %} <p style="color: red"><i class="fa fa-times mr-1"></i>Le stage n'a pas mené à une embauche</p>
                        {% endif %}
                    </div>
                </div>
                {% if stage.mailVisible %}
                    <div class="row ml-1 mt-4">
                        <p><strong>Tuteur entreprise du stage: </strong> {{ stage.nomTuteurEnt }} {{ stage.prenomTuteurEnt }} </p>
                    </div>
                    <div class="row ml-1 mt-2">
                        <div class="col text-center">
                            <i class="fa fa-mobile mr-1"></i> {{ stage.telTuteurEnt }}
                        </div>
                        <div class="col text-center">
                            <i class="fa fa-envelope mr-1"></i> {{ stage.mailTuteurEnt }}
                        </div>
                    </div>
                {% endif %}
                <div class="row ml-1 mt-4">
                    <p><strong>Thèmes: </strong> {% for theme in stage.themes %}{{ theme.theme }} - {% else %}Aucun thème associé{% endfor %}</p>
                </div>
                <div class="row ml-1 mt-4">
                    <p><strong>Mots-clés: </strong> {% for motCle in stage.motsCles %}{{ motCle.motCle }} - {% else %}Aucun mot-clé associé{% endfor %}</p>
                </div>
                <div class="row ml-1 mt-4">
                    <p><strong>Commentaire: </strong></p>
                </div>
                <div class="bulle-commentaire">
                    {{ stage.commentaire }}
                </div>
                <div class="row mt-4 mb-4">
                    {% if stage.recap %}
                        <a href="{{ stage.recap }}">Accéder au récapitulatif</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}